apiVersion: v1
kind: Pod
metadata:
  name: portal-noticias
  labels:
    name: portal-noticias
spec:
  containers:
  - name: portal-noticias
    image: aluracursos/portal-noticias:1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
